name = input("---> what is your name?")
print(f"Hello!{name}, welcome to comp thinking!")
input("")
print("Today we will make a short story with your help")
print("")
print("")
person = input("pick a person: ")
location = input ("now pick a location: ")
print("------------------------------------------------")
print(f"One day,{person} walked into {location}...")
input("")
print("Now I shall tell a joke")
print("what do you call a fish with no eyes?")
input("")
print("fshhhh!")
print("thank you, thank you!")