name = input("---> what is your name?")
print(f"Hello!{name}, welcome to comp thinking!")
print("Today we will make a short story with your help")
print("")
print("")
person = input("pick a person: ")
location = input ("now pick a location: ")
print("------------------------------------------------")
print(f"One day,{person} walked into {location}...")